import type { Metadata } from 'next';
import { Provider } from '@/components/ui/provider';
import { Toaster } from '@/components/ui/toaster';
import { AuthProvider } from '../provider/auth.provider';
import { ContactProvider } from '../provider/contact.provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body>
        <AuthProvider>
          <ContactProvider>
            <Provider>
              <Toaster />
              {children}
            </Provider>
          </ContactProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
